val_image: 'Data/txt_scripts/val.txt'
val_pts: 'Data/txt_scripts/LASO_Point_val.txt'
human_3DIR: 'Data/smplh_param/human_label.json'
behave: 'Data/Behave/behave.json'
desc_file: 'Data/txt_scripts/human_object_desc.json'
best_checkpoint: 'runs/LEMON/AUC_best.pt'
run_type: 'infer'
contact_result_folder: 'Outputs/Human/'
affordance_result_folder: 'Outputs/Object/'
spatial_result_folder: 'Outputs/Spatial/'
emb_dim: 512
infer_type: 'batch'
model: 'laso'
